# Generated by Django 6.0.3 on 2026-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='seller',
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', '取引中'), ('completed', '取引完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
