# Generated by Django 6.0.3 on 2026-03-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_block_product_town"),
        ("trades", "0002_remove_trade_seller_alter_trade_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "取引",
                "verbose_name_plural": "取引一覧",
            },
        ),
        migrations.AddField(
            model_name="trade",
            name="seller",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="出品者",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="購入者",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="取引開始日時"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="price",
            field=models.PositiveIntegerField(verbose_name="取引価格"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="products.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "支払い待ち"),
                    ("paid", "支払い済み"),
                    ("shipped", "発送済み"),
                    ("completed", "取引完了"),
                    ("cancelled", "キャンセル"),
                ],
                default="pending",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="メッセージ内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="送信者",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="trades.trade",
                        verbose_name="取引",
                    ),
                ),
            ],
            options={
                "verbose_name": "メッセージ",
                "verbose_name_plural": "メッセージ一覧",
                "ordering": ["created_at"],
            },
        ),
    ]
