# Generated by Django 6.0.3 on 2026-03-31 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_location"),
        ("trades", "0005_trade_unique_active_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trade",
            name="unique_active_trade_per_product",
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "支払い済み"),
                    ("shipped", "発送済み"),
                    ("completed", "取引完了"),
                    ("cancelled", "キャンセル"),
                ],
                default="paid",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["paid", "shipped"])),
                fields=("product",),
                name="unique_active_trade_per_product",
            ),
        ),
    ]
