# Generated by Django 6.0.3 on 2026-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_company_name_user_corporate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
