# Generated by Django 6.0.3 on 2026-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_latitude_product_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="address_line",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="prefecture",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
