# Generated by Django 6.0.3 on 2026-03-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_address_line_product_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="block",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="town",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
